title: Codes with Dogs
email: jacqueline.a.potts@gmail.com
description: The ramblings of a software engineer and tales of Ruby, working at start-ups, making code more better and having fun with her dogs.
baseurl: ""
url: "https://jpotts244.github.io"
github_username:  jpotts244

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
